"use client";

import { act, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { X } from "lucide-react";

interface EnrollButtonProps {
    patientId: string;
}

export default function EnrollButton({ patientId }: EnrollButtonProps) {
    const supabase = createClient();
    const [showModal, setShowModal] = useState(false);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const openModal = () => {
        setError(null);
        setShowModal(true);
    };

    const closeModal = () => {
        if (loading) return;
        setShowModal(false);
        setError(null);
    };

    const sendEnroll = async () => {
        setLoading(true);
        setError(null);
        try {
            const { error: enrollError } = await supabase
                .from("device_commands")
                .update({ enroll: true })
                .eq("user_id", patientId);

            if (enrollError) {
                console.error("Failed to trigger enroll:", enrollError);
                setError(enrollError.message ?? "Failed to trigger enroll");
                return;
            }

            setShowModal(false);
            alert("Enroll triggered successfully");
        } catch (e) {
            console.error("Error triggering enroll", e);
            setError("Error triggering enroll");
        } finally {
            setLoading(false);
        }
    };

    /*
        Log what action a caregiver takes for a patient

        ---------------------- caregiver_logs ----------------------
         * id: int                      (auto generated by database)
         * caregiver_id: uuid           FK to users id
         * patient_id: uuid             from patientId
         * device_id: text              NULLABLE   
         * action: text
         * event_id: uuid               NULLABLE
         * event_status: text           NULLABLE
         * details: text               NULLABLE
         * created_at: timestampz
        ------------------------------------------------------------
    */
    // const logAction = async (action: string, details: string) => {
    //     try {
    //         const payload = events.map((e) => {
    //             const eventId = null;
    //             const eventStatus = null;
    //             const deviceId = null;

    //             if (action=='emergency_open' || action=='enroll') {
    //                 // set eventId, eventStatus, and deviceId
    //             }

    //             return {
    //                 caregiver_id: userId,
    //                 patient_id: patientId,
    //                 device_id: deviceId,
    //                 action: action,
    //                 event_id: null || eventId,
    //                 event_status: null || eventStatus,
    //                 details:    details
    //             }
    //         });


    //         const { error: logError } = await supabase
    //             .from("caregiver_logs")
    //             .insert(payload)

    //         if (logError) console.error("Failed to log Action", logError);
    //     } catch (e) {
    //         console.error("Failed to log event successfully", e);
    //         setError("Error logging event");

    //     }
    // }

    return (
        <>
            <Button
                variant="outline"
                size="default"
                onClick={openModal}
                disabled={loading}
            >
                Enroll New Finger
            </Button>

            {showModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={() => closeModal()} aria-hidden />

                    <Card className="relative w-full max-w-2xl">
                        <CardHeader className="relative">
                            <Button
                                type="button"
                                variant="ghost"
                                size="icon"
                                onClick={closeModal}
                                disabled={loading}
                                aria-label="Close dialog"
                                className="absolute top-4 right-4"
                            >
                                <X className="h-4 w-4" />
                            </Button>
                            <CardTitle id="modal-title" className="text-2xl text-primary pr-12">
                                Please Read These Instructions
                            </CardTitle>
                            <CardDescription className="mt-2">
                                Follow the steps below to enroll a new fingerprint on the device.
                            </CardDescription>
                        </CardHeader>

                        <CardContent>
                            <div className="mb-6 p-4 bg-primary/10 border-l-4 border-primary rounded-lg">
                                <ol className="list-decimal list-inside text-base space-y-3 leading-relaxed">
                                    <li>Press "Send Enroll Command" below.</li>
                                    <li>Immediately place the user's finger on the device sensor.</li>
                                    <li>When the sensor flashes red, remove the finger briefly, then place it back on the sensor.</li>
                                    <li>Once the sensor turns green, the enrollment is complete.</li>
                                    <li>Test the fingerprint to confirm it works.</li>
                                </ol>
                            </div>

                            {error ? (
                                <div className="text-sm text-destructive mb-4 p-3 bg-destructive/10 rounded-lg border border-destructive/20 font-medium">
                                    {error}
                                </div>
                            ) : null}
                        </CardContent>

                        <CardFooter className="flex justify-center">
                            <Button
                                type="button"
                                variant="default"
                                size="lg"
                                onClick={sendEnroll}
                                disabled={loading}
                            >
                                {loading ? "Sending..." : "Send Enroll Command"}
                            </Button>
                        </CardFooter>
                    </Card>
                </div>
            )}
        </>
    );
}